language: python
python:
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
 - "pypy"
install:
 - pip install -r requirements.txt
 - pip install --force-reinstall "coverage>=4.0,<4.4" codeclimate-test-reporter
script:
 - python setup.py nosetests
 - python setup.py sdist
after_success:
 - codeclimate-test-reporter
 - |
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      if [ "$TRAVIS_PYTHON_VERSION" == "2.7" ]; then
        pip install wheel twine
        python setup.py bdist bdist_wheel
        twine upload -u $PYPI_USER -p $PYPI_PWD dist/*
      fi
    fi

