language: python
python:
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
 - "pypy"
install:
 - pip install -r requirements.txt
 - pip install --force-reinstall "coverage>=4.0,<4.4" codeclimate-test-reporter
script:
 - python setup.py nosetests
 - python setup.py sdist bdist bdist_wheel
after_success:
 - codeclimate-test-reporter
notifications:
  slack: digicort:lbgdFcFmWmHtHKDEMI3FwQK5